name: eco_friendly_habit_tracker
description: A Flutter app for tracking eco-friendly habits.

environment:
  sdk: "^3.4.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.0
  cloud_firestore: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter:
#   assets:
#     - assets/images/
#     - assets/fonts/